version: '3.9'
services:
  db:
    image: 'postgres:14'
    env_file: .env
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/data:ro
      - ./entrypoint.d/:/docker-entrypoint-initdb.d:ro

volumes:
  postgres-data: {}