version: '3.9'

services:
  db:
    image: postgres:14
    env_file: .env
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./data:/data:ro
      - ./entrypoint.d/:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    image: node:lts
    user: 'node'
    working_dir: /STOR_repo
    env_file: .env
    environment:
      - NODE_ENV=development
      - DB_HOST=db  # Ensure this is set if your Node.js app uses this env var to connect to Postgres
    depends_on:
      - db
    ports:
      - '3000:3000'
    volumes:
      - ./:/STOR_repo
    command: 'npm start'

volumes:
  postgres-data: {}
